## Imports

In [5]:
from bs4 import BeautifulSoup
from time import sleep

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

from tqdm import tqdm

import pandas as pd
from geopy import geocoders
import requests
import re

## Selenium Setup

In [6]:
def openChrome():
    portz = 9995
    chromeOptions = webdriver.ChromeOptions()
    chromeOptions.add_argument(f'--remote-debugging-port={portz}')
    chromeOptions.add_experimental_option("excludeSwitches", ["enable-automation"])
    chromeOptions.add_argument("--disable-blink-features=AutomationControlled")
    chromeOptions.add_argument("--disable-blink-features")
    # chromeOptions.add_argument("--headless")

    prefs = {"profile.managed_default_content_settings.images": 2}
    chromeOptions.add_experimental_option("prefs", prefs)

    driver = webdriver.Chrome(executable_path=r"C:\Users\kylew\OneDrive\Desktop\Advent\chromedriver.exe", options=chromeOptions)    
    driver.set_window_rect(0, 0, width=360, height=600)
    driver.set_page_load_timeout(66)
    return driver

## Scraper Code

In [7]:
# On the new tab that opens - login to RCA
# Move over to the transactions tab and pull up the table view (3 lines)
# Hit the enter key on the code below and the scrape will start

In [ ]:
driver = openChrome()
list_write = []

url =  f'https://app.rcanalytics.com/home'
driver.get(url)
sleep(1)
input("Login Select And Enter Continue")

driver.set_window_rect(0, 0, width=1222, height=999)

output_file_path = 'rca_transactions.xlsx'
with pd.ExcelWriter(output_file_path, engine='xlsxwriter') as writer:
    pass

list_pname = []
while 1:
    page_source  = driver.page_source
    soup = BeautifulSoup(page_source, 'html.parser')
    data = soup.find_all("tr",attrs={"ng-click": "pinTransactionsTableController.onSelectTransactionRow(row.data.transaction);"})
    stt_nb = 1
    for item in data:
        stt_text, date_s, p_type = "", "", ""
        transaction = item.find("td", class_="transaction")
        transaction = transaction.find_all("span", attrs={"tooltip-placement": "top-left"})
        if transaction != None:
            stt_text = transaction[0].text
            date_s = transaction[1].text
            p_type = transaction[2].text

        p_name, address_1, address_2 = "", "", ""
        address_list = item.find("td", class_="address")
        pname = address_list.find("a", attrs={"target": "_blank"})
        link_s = pname.get("href")
        p_name = pname.text

        address_list = address_list.find_all("span", attrs={"tooltip-placement": "top-left"})
        try:
            address_1 = address_list[1].text
        except:
            address_1 = ""
        try:
            address_2 = address_list[2].text
        except:
            address_2 = ""
        address = address_1 + " " + address_2
        if p_name not in list_pname:
            list_pname.append(p_name)
            stt_nb += 1

            sf, year_blt, flrs = "", "", ""
            info = item.find("td", class_="propertyInfo")
            info = info.find_all("span", attrs={"tooltip-placement": "top-left"})
            try:
                sf = info[0].text
            except:
                sf = ""
            try:
                year_blt = info[1].text
            except:
                year_blt = ""
            try:
                flrs = info[2].text
            except:
                flrs = ""

            price, sf_unit, cap = "", "", ""
            i_price = item.find("td", class_="transactionPrice")
            i_price = i_price.find_all("span", attrs={"tooltip-placement": "top-left"})
            if i_price != None:
                for pc in i_price:
                    t_pc = pc.text
                    if "sf" in t_pc or "unit" in t_pc:
                        sf_unit = t_pc
                    elif "confm'd" in t_pc or "approx" in t_pc:
                        price = t_pc
                    else:
                        cap = t_pc

            buyer, seller, ledder = "", "", ""
            entities = item.find("td", class_="entities")
            entities = entities.find_all("div", attrs={"ng-repeat": "item in row.data.transaction.PlayersFormatted"})
            for en in entities:
                img_buy = en.find("img", attrs={"src": "/assets/images/bsb/icon_owner.svg"})
                if img_buy != None:
                    buyer = img_buy.find_next("span").text

                img_sell = en.find("img", attrs={"src": "/assets/images/bsb/icon_seller.svg"})
                if img_sell != None:
                    seller = img_sell.find_next("span").text

                img_led = en.find("img", attrs={"src": "/assets/images/bsb/icon_lender.svg"})
                if img_led != None:
                    ledder = img_led.find_next("span").text

            comments = ""
            comments = item.find("td", class_="comments")
            if comments != None:
                comments = comments.text

            list_write = []
            list_write.append([stt_text, date_s, p_type, p_name, address, sf, year_blt, flrs,  price, sf_unit, cap, buyer, seller, ledder, comments])
            rows = list(zip(*list_write))
            cols_names = ['Transaction Type', 'Transaction Date', 'Property Type', 'Property Name', 'Address', 'SF / Units', 'Year Blt/Reno', '#Buildings/Flrs', 'Price', '$/SF/Units', 'Cap Rate', 'Owner/Buyer', 'Seller', 'Lender', 'Comments']
            df_new_rows = pd.DataFrame(dict(zip(cols_names, rows)))

            df_existing = pd.read_excel(output_file_path)
            df_combined = pd.concat([df_existing, df_new_rows], ignore_index=True)
            df_combined.to_excel(output_file_path, index=False)

    kkk = 1
    while 1:
        try:
            element = WebDriverWait(driver,0.1).until(
                EC.presence_of_element_located((By.XPATH, f"(//tr[@ng-click='pinTransactionsTableController.onSelectTransactionRow(row.data.transaction);'])[{kkk}]"))
            )
        except:
            driver.execute_script("arguments[0].scrollIntoView();", element) 
            break
        kkk += 1

input("Done")

## Add Latitude and Longitude

In [4]:
df = pd.read_excel(r"C:\Users\kylew\OneDrive\Desktop\MLSA\Scripts\rca.xlsx")
df

,Transaction Type,Transaction Date,Property Type,Property Name,Address,SF / Units,Year Blt/Reno,#Buildings/Flrs,Price,$/SF/Units,Cap Rate,Owner/Buyer,Seller,Lender,Comments
0,Refinance,Sep '23,Industrial,1000 North Highway 77,"1000 North Hwy 77 Hillsboro, TX 76645 USA","117,060 sf",,NaN,NaN,NaN,,Joseph Ravitsky,NaN,NewtekOne,Warehouse property;
1,Refinance,Nov '23,Industrial,1001 Webster Avenue,"1001 Webster Ave Waco, TX 76706 USA","54,294 sf",1898,1 bldg/1 flr,NaN,NaN,,Ryan Gibson,NaN,Independent Financial,Warehouse property; buyer assumed mtg; prior s...
2,Sale,Nov '23,Industrial,101 North Highway 146,"101 N Hwy 146 Texas City, TX 77590 USA","36,500 sf",1972/2022,NaN,NaN,NaN,private,Benito X Valadez,TJC Captial Management LLC,NaN,Warehouse/mfg property;
3,Sale,Nov '23,Industrial,10130 West Gulf Bank Road,"10130 W Gulf Bank Rd Houston, TX 77040 USA","34,482 sf",1980,1 bldg/1 flr,NaN,NaN,,Russell W Griffin,10130 West Gulf Bank-2019 LP,Texas Security Bank,Warehouse property; prior sale: Oct-19;
4,Sale,Oct '23,Industrial,10355 Deer Trail Dr,"10355 Deer Trail Dr Houston, TX 77038 USA","62,255 sf",,NaN,$8.4 confm'd,$135 /sf,,Interglass Corp,Rycore Capital,NaN,Warehouse property;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,Construction,Nov '23,Industrial,Waxahachie,"I-35 Midlothian, TX 76065 USA",NaN,Underway,4 bldgs,NaN,NaN,,Blue Star Investments,NaN,NaN,Est Completion: Q4 2024; Warehouse property;
402,Construction,Oct '23,Industrial,WC T Project Warehouse,"1530 FM973 Taylor, TX 76574 USA","70,000 sf",Underway,1 bldg/1 flr,NaN,NaN,,Samsung Group,NaN,NaN,Est Completion: Q4 2024; Warehouse/distributio...
403,Construction,Oct '23,Industrial,West Loop Business Park,"724 Jim Wright Fwy White Settlement, TX 76108...","140,000 sf",Underway,14 bldgs/1 flr,NaN,NaN,,Street Realty,NaN,FirstBank Southwest,Est Completion: Q4 2024; Flex property; prior ...
404,Sale,Nov '23,Hotel,Whitten Inn Cotulla RV Park,"145 FM468 Cotulla, TX 78014 USA",60 units,2015,2 bldgs/2 flrs,NaN,NaN,,Areli P Villa,Super 5 LLC,Woori Financial,Limited Service property; prior sale: Aug-17;
405,Sale,Oct '23,Industrial,Woodlands Design Center,"30643 FM2978 Magnolia, TX 77354 USA","9,028 sf",2016,3 bldgs/1 flr,NaN,NaN,,Jose a L Solorio,Justin Tipler,Mint National Bank,"Warehouse/showroom property; Tenants: Tipler, ..."

In [5]:
geolocator = geocoders.GoogleV3(api_key='AIzaSyBM9LfiT56LWHu73cOpTwpiB_wBEbncqWg')

In [6]:
latitude = []
longitude = []

with tqdm(total=len(df)) as pbar:
    for index, row in df.iterrows():
        url = str(row['Address'])
        try:
            location = geolocator.geocode(url)
            latitude.append(location.latitude)
            longitude.append(location.longitude)
        except: 
            print("Error finding latitude/longitude for: ", row['Address'])
            latitude.append('')
            longitude.append('')
            
        pbar.update(1)

100%|██████████| 406/406 [01:09<00:00,  5.87it/s]

In [7]:
df['latitude'] = latitude
df['longitude'] = longitude
df

,Transaction Type,Transaction Date,Property Type,Property Name,Address,SF / Units,Year Blt/Reno,#Buildings/Flrs,Price,$/SF/Units,Cap Rate,Owner/Buyer,Seller,Lender,Comments,latitude,longitude
0,Refinance,Sep '23,Industrial,1000 North Highway 77,"1000 North Hwy 77 Hillsboro, TX 76645 USA","117,060 sf",,NaN,NaN,NaN,,Joseph Ravitsky,NaN,NewtekOne,Warehouse property;,32.024201,-97.124076
1,Refinance,Nov '23,Industrial,1001 Webster Avenue,"1001 Webster Ave Waco, TX 76706 USA","54,294 sf",1898,1 bldg/1 flr,NaN,NaN,,Ryan Gibson,NaN,Independent Financial,Warehouse property; buyer assumed mtg; prior s...,31.549477,-97.133010
2,Sale,Nov '23,Industrial,101 North Highway 146,"101 N Hwy 146 Texas City, TX 77590 USA","36,500 sf",1972/2022,NaN,NaN,NaN,private,Benito X Valadez,TJC Captial Management LLC,NaN,Warehouse/mfg property;,29.384906,-94.951894
3,Sale,Nov '23,Industrial,10130 West Gulf Bank Road,"10130 W Gulf Bank Rd Houston, TX 77040 USA","34,482 sf",1980,1 bldg/1 flr,NaN,NaN,,Russell W Griffin,10130 West Gulf Bank-2019 LP,Texas Security Bank,Warehouse property; prior sale: Oct-19;,29.879761,-95.550172
4,Sale,Oct '23,Industrial,10355 Deer Trail Dr,"10355 Deer Trail Dr Houston, TX 77038 USA","62,255 sf",,NaN,$8.4 confm'd,$135 /sf,,Interglass Corp,Rycore Capital,NaN,Warehouse property;,29.917470,-95.424172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,Construction,Nov '23,Industrial,Waxahachie,"I-35 Midlothian, TX 76065 USA",NaN,Underway,4 bldgs,NaN,NaN,,Blue Star Investments,NaN,NaN,Est Completion: Q4 2024; Warehouse property;,31.967535,-97.119490
402,Construction,Oct '23,Industrial,WC T Project Warehouse,"1530 FM973 Taylor, TX 76574 USA","70,000 sf",Underway,1 bldg/1 flr,NaN,NaN,,Samsung Group,NaN,NaN,Est Completion: Q4 2024; Warehouse/distributio...,30.532934,-97.446720
403,Construction,Oct '23,Industrial,West Loop Business Park,"724 Jim Wright Fwy White Settlement, TX 76108...","140,000 sf",Underway,14 bldgs/1 flr,NaN,NaN,,Street Realty,NaN,FirstBank Southwest,Est Completion: Q4 2024; Flex property; prior ...,32.771636,-97.474398
404,Sale,Nov '23,Hotel,Whitten Inn Cotulla RV Park,"145 FM468 Cotulla, TX 78014 USA",60 units,2015,2 bldgs/2 flrs,NaN,NaN,,Areli P Villa,Super 5 LLC,Woori Financial,Limited Service property; prior sale: Aug-17;,28.444958,-99.251926
405,Sale,Oct '23,Industrial,Woodlands Design Center,"30643 FM2978 Magnolia, TX 77354 USA","9,028 sf",2016,3 bldgs/1 flr,NaN,NaN,,Jose a L Solorio,Justin Tipler,Mint National Bank,"Warehouse/showroom property; Tenants: Tipler, ...",30.196429,-95.588027

In [8]:
df.to_csv(r"C:\Users\kylew\OneDrive\Desktop\MLSA\Scripts\RCA_Scrape.csv", index=False)

# Ali's Code

In [ ]:
import requests
import json
import pandas as pd

url = "https://app.rcanalytics.com/api/v1/propertySearch/search"

payload = {
  "RequestType": 0,
  "MapBounds": {
    "northeast": {
      "latitude": 73.92246884621464,
      "longitude": 109.3359375
    },
    "southwest": {
      "latitude": -73.92246884621464,
      "longitude": -109.3359375
    }
  },
  "CenterPoint": {
    "latitude": None,
    "longitude": None
  },
  "MapZoom": 2,
  "SortOrder": {
    "Field": "StatusDate",
    "Desc": True
  },
  "IncludePins": True,
  "IncludeBubbles": False,
  "SearchGeoShape": None,
  "PropertyTypeFilter": [],
  "PrimaryPropertyTypeFilter": [],
  "TransactionSearchFilters": {
    "CondoConversions": None,
    "Redevelopment": None,
    "ToBeDemolished": None,
    "Conversion": None,
    "Occupancy": None,
    "Renovation": None,
    "PendingTransactions": False,
    "ClosedTransactions": False,
    "TerminatedTransactions": False,
    "TypeSale": False,
    "TypeRefinancing": False,
    "TypeTransfer": False,
    "TypeConstruction": False,
    "IndividualProperty": False,
    "Portfolio": False,
    "EntityLevel": False,
    "FullLongTerm": None,
    "FullShortTerm": None,
    "PartialLeaseback": None,
    "MinorityInterest": None,
    "MajorityInterest": None,
    "DateRange": {
      "StartDate": "2024-03-07",
      "EndDate": "2025-03-07",
      "DateRangeType": 14
    },
    "PreviousDateRange": None,
    "MinPrice": None,
    "MaxPrice": None,
    "MinPPU": None,
    "MaxPPU": None,
    "MinCapRate": None,
    "MaxCapRate": None,
    "ForwardSale": None,
    "ResolvedDistress": None,
    "TopBuyersDateRange": None,
    "TopSellersDateRange": None,
    "ConstructionDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "ExcludeNAPrices": None
  },
  "CapitalGroupFilters": {
    "CapitalRole": "buyers",
    "CapitalSourceTypes": [],
    "CBGeographyInclude": [],
    "CBGeographyExclude": [],
    "JvSearchType": None
  },
  "InvestorGroupFilters": [],
  "PropertyDetailsFilter": {
    "YearBuiltMin": None,
    "YearBuiltMax": None,
    "YearRenovatedMin": None,
    "YearRenovatedMax": None,
    "UnitsMin": None,
    "UnitsMax": None,
    "FloorsMin": None,
    "FloorsMax": None,
    "Breeam": False,
    "Leed": False,
    "EnergyStar": False,
    "TenantNames": [],
    "CondoInterest": False,
    "LeasedFee": False,
    "LeaseHold": False,
    "OwnershipFee": False,
    "SingleTenant": False,
    "MultiTenant": False,
    "QScoreMin": 0,
    "QScoreMax": 100,
    "WalkScoreMin": 0,
    "WalkScoreMax": 100,
    "TransitScoreMin": 0,
    "TransitScoreMax": 100,
    "OccupancyMin": None,
    "OccupancyMax": None,
    "MixedUse": None,
    "ConstructionStatus": None,
    "HoldTimeMin": None,
    "HoldTimeMax": None,
    "OpportunityZone": None
  },
  "GreenRatingCategoryFilters": [],
  "RolesQueryWordFilters": [],
  "KeywordQueryWordFilters": [],
  "IncludeGeographyFilterItems": [],
  "ExcludeGeographyFilterItems": [],
  "CompanyIncludeGeographyFilterItems": [],
  "CompanyExcludeGeographyFilterItems": [],
  "CompanyPortfolioSizeSearchFilters": {
    "PropertyType": None,
    "UnitsMin": None,
    "UnitsMax": None,
    "SquareFootMin": None,
    "SquareFootMax": None,
    "PropertiesMin": None,
    "PropertiesMax": None,
    "TotalEstValueMin": None,
    "TotalEstValueMax": None
  },
  "CurrencyId": 1,
  "MeasurementUnitId": 1,
  "DateFormat": "MM/DD/YYYY",
  "HotelFilters": {
    "hotelFranchises": []
  },
  "LoanFilters": {
    "LoanAmountMin": None,
    "LoanAmountMax": None,
    "LoanTypes": [],
    "SyntheticLoanStatuses": [],
    "LoanPaymentStatuses": {
      "Day30": None,
      "Day60": None,
      "Day90": None,
      "Day120": None
    },
    "OriginationDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "DefeasanceDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "PrepayDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "DistressDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "MaturityDateRange": {
      "StartDate": None,
      "EndDate": None,
      "DateRangeType": None
    },
    "LenderGroups": [],
    "InterestRateTypes": [],
    "InterestRateMin": None,
    "InterestRateMax": None,
    "LikelyRefi": False,
    "ServicerNotesInclude": [],
    "ServicerNotesExclude": [],
    "Resolved": False
  },
  "ClimateFilter": {
    "AggregateRiskMin": None,
    "AggregateRiskMax": None,
    "OverallPhysicalRiskMin": None,
    "OverallPhysicalRiskMax": None,
    "CoastalFloodingMin": None,
    "CoastalFloodingMax": None,
    "FluvialFloodingMin": None,
    "FluvialFloodingMax": None,
    "TropicalCyclonesMin": None,
    "TropicalCyclonesMax": None,
    "ExtremeHeatMin": None,
    "ExtremeHeatMax": None,
    "ExtremeColdMin": None,
    "ExtremeColdMax": None,
    "WildfireMin": None,
    "WildfireMax": None
  },
  "PropertiesRequestType": 1,
  "Size": 500
}

from datetime import datetime, timedelta
import json
current_date = datetime.strptime("2024-03-07", "%Y-%m-%d")
end_date = datetime.strptime("2025-03-07", "%Y-%m-%d")
data_f = []
while current_date < end_date:
    next_period = current_date + timedelta(days=5)
    if next_period > end_date:
        next_period = end_date
    
    payload["TransactionSearchFilters"]["DateRange"]["StartDate"] = current_date.strftime("%Y-%m-%d")
    payload["TransactionSearchFilters"]["DateRange"]["EndDate"] = next_period.strftime("%Y-%m-%d")
    
    payload_js = json.dumps(payload, indent=2)
    headers = {
      'accept': 'application/json, text/plain, */*',
      'accept-language': 'en-US,en;q=0.9',
      'content-type': 'application/json;charset=UTF-8',
      'origin': 'https://app.rcanalytics.com',
      'priority': 'u=1, i',
      'referer': 'https://app.rcanalytics.com/transactions?lat=0&lon=0&zoom=2&view=fulltable&ne=109.3359375,73.92246884621464&sw=-109.3359375,-73.92246884621464',
      'sec-ch-ua': '"Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"',
      'sec-ch-ua-mobile': '?0',
      'sec-ch-ua-platform': '"Windows"',
      'sec-fetch-dest': 'empty',
      'sec-fetch-mode': 'cors',
      'sec-fetch-site': 'same-origin',
      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
      'Cookie': '_ga=GA1.2.1453816737.1741360862; _gid=GA1.2.951863000.1741360862; _legacy_auth0.dylBYqw5EzveSNFsMBGpluStVK8wakYh.is.authenticated=True; auth0.dylBYqw5EzveSNFsMBGpluStVK8wakYh.is.authenticated=True; rca-da=59a01f90-2dbf-4dad-acc4-dea2f073b043; GCLB=CLbx1vfxw66EKBAD; rcajwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VXNlcl9pZCI6MTUxNTAzLCJhY2NvdW50X2lkIjoyNTQ5OSwiZmlyc3ROYW1lX3R4IjoiUm9iZXJ0IiwibGFzdE5hbWVfdHgiOiJNYWdlZSIsImFjY291bnRBZG1pbl9mZyI6MSwic3lzdGVtQWRtaW5fZmciOjAsImxlZ2FjeVBhc3NLZXkiOiJFQ2NZeUFCb0dvK211bDRPMjRpSitnJCQiLCJydWxlcyI6W10sInNjb3BlIjpbIlBUUyIsIkxvYW4iLCJMb2FuRmVhdHVyZSIsIklVIiwiVFQiLCJUcmFja2VyIiwiVXNlclBhc3N3b3JkQ29udHJvbCIsIkRldmljZUF1dGgiLCJUVF9zYWxlcyIsIlRUX2NvbnN0cnVjdGlvbiIsIlRUX2xvYW5zIiwiUHJvcGVydHlTdXJ2ZWlsbGFuY2UiLCJNTUEiXSwiemlwQ29uZmlybWVkX2ZnIjp0cnVlLCJkZXZpY2VBdXRoQ29uZmlybWVkX2ZnIjp0cnVlLCJleGNlbEV4cG9ydFJvd3MiOm51bGwsImxvZ2luQWxsb3dlZF9mZyI6MSwibW9iaWxlTG9naW5Pbmx5X2ZnIjowLCJlbWFpbCI6ImJvYmJ5QG1sc2F2ZW50dXJlcy5jb20iLCJhdXRoU2Vzc2lvbklkIjoiZTk1MTJmZjAtZmI2Ny0xMWVmLWJkNjMtODU0YWYwMTFiN2E4Iiwic2Vzc2lvbklkIjoiYjFlNWQyYzYtYjM3Mi00ZWU0LTkwMTctNTc1NDVlNGNkYzEwIiwibGRIYXNoIjoiMDA3ODRjNTAwYjk5YTg4ZWI0Yjc4ODJiNzNkMWFjYzdjNDNkNTk4YTBiZTQ3OWMwY2IxNmU4YmE2YzllYmEwNCIsImV4cCI6MTc0MTQ1MjYxMiwiaWF0IjoxNzQxMzYwOTE4fQ.KLqcbM2KTH3dqaxbCJaFyJKqG3EEhNfT6CZCty35VCI; rcajwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VXNlcl9pZCI6MTUxNTAzLCJhY2NvdW50X2lkIjoyNTQ5OSwiZmlyc3ROYW1lX3R4IjoiUm9iZXJ0IiwibGFzdE5hbWVfdHgiOiJNYWdlZSIsImFjY291bnRBZG1pbl9mZyI6MSwic3lzdGVtQWRtaW5fZmciOjAsImxlZ2FjeVBhc3NLZXkiOiJFQ2NZeUFCb0dvK211bDRPMjRpSitnJCQiLCJydWxlcyI6W10sInNjb3BlIjpbIlBUUyIsIkxvYW4iLCJMb2FuRmVhdHVyZSIsIklVIiwiVFQiLCJUcmFja2VyIiwiVXNlclBhc3N3b3JkQ29udHJvbCIsIkRldmljZUF1dGgiLCJUVF9zYWxlcyIsIlRUX2NvbnN0cnVjdGlvbiIsIlRUX2xvYW5zIiwiUHJvcGVydHlTdXJ2ZWlsbGFuY2UiLCJNTUEiXSwiemlwQ29uZmlybWVkX2ZnIjp0cnVlLCJkZXZpY2VBdXRoQ29uZmlybWVkX2ZnIjp0cnVlLCJleGNlbEV4cG9ydFJvd3MiOm51bGwsImxvZ2luQWxsb3dlZF9mZyI6MSwibW9iaWxlTG9naW5Pbmx5X2ZnIjowLCJlbWFpbCI6ImJvYmJ5QG1sc2F2ZW50dXJlcy5jb20iLCJhdXRoU2Vzc2lvbklkIjoiZTk1MTJmZjAtZmI2Ny0xMWVmLWJkNjMtODU0YWYwMTFiN2E4Iiwic2Vzc2lvbklkIjoiYjFlNWQyYzYtYjM3Mi00ZWU0LTkwMTctNTc1NDVlNGNkYzEwIiwibGRIYXNoIjoiMDA3ODRjNTAwYjk5YTg4ZWI0Yjc4ODJiNzNkMWFjYzdjNDNkNTk4YTBiZTQ3OWMwY2IxNmU4YmE2YzllYmEwNCIsImV4cCI6MTc0MTQ1MjkyNSwiaWF0IjoxNzQxMzYwOTE4fQ.g2x5ijUUcyEppxqxVQk8_YwDticeKWVaTLcBhef2kUQ'
    }
    
    response = requests.request("POST", url, headers=headers, data=payload_js)
    
    data = json.loads(response.text)
    data_f.extend(data["data"]["pinTransactionItems"])
    print(len(data_f),current_date.strftime("%Y-%m-%d"),next_period.strftime("%Y-%m-%d"))
    current_date = next_period
    
data_ff =[]
for i in data_f:
    if i not in data_ff:
        data_ff.append(i)


df = pd.DataFrame(data_ff)

df.to_csv("Transactions.csv")

In [58]:
# Changing column names adjusted for Snowflake import
# Preparing data for Snowflake entry
# Creating CSV for Snowflake import 
import numpy as np
import pandas as pd
import ast
import re
from bs4 import BeautifulSoup

In [59]:
columns_to_load = [
    "_id", "BuyerCapitalGroup", "SellerCapitalGroup", "PropertyId", 
    "DealId", "PropertyKeyId", "Longitude", "Latitude", "GeoCodeQuality", "TransactionStatus", 
    "TransactionType", "TransactionSubtype", "StatusDateString", "LastModifiedDateString", 
    "PropertyType", "PropertyTypeFull", "PropertyTypeCode", "PropertyTypeAbbreviated", "PropertySubType", 
    "PropertyTypeSearchIds", "ConstructionStatusId", "Market", "SubMarket", "PropertyName", "Address", 
    "City", "StateProv", "County", "Country", "CountryCode", "PostalCode", "CreateDateString", 
    "IsMeasurementUnits", "Units", "Sf", "UnitsCombined", "NumberBuildings", 
    "NumberFloors", "StatusPrice", "StatusPriceAdjusted", "StatusPriceQualifier", "StatusPricePerUnit", 
    "StatusPricePerSF", "StatusCapRate", "StatusCapRateQualifier", "BuyerSellerBrokerString", "PropertyComments", 
    "DealComments", "YearBuilt", "YearRenovated", "QScore", "Feature", "CurrencyId", "MeasurementId", 
    "Deed", "MSA", "CBSA", "LandAreaAcres", "OccupancyRate", "PartialInterest_pct", "BuildableAreaUS", 
    "APNs", "Buyers", "Sellers", "Lenders", "BuyerBrokers", "SellerBrokers", 
    "HasPortfolio", "NumberOfProps", "MixedPropertyType", "FirstMortgageLoan_amt", 
    "PriorSalePrice_amt", "ProjectCost_amt", "StreetRetailArea_dbl", 
    "MeetingSpaceArea_dbl", "EstCompletionDate", "IsCBD", "AdminLevel0Id", 
    "AdminLevel1Id", "MetroId", "TransTypeId", "TenantsFull", "TenantsMetric", "TenantsTsubo", "TenantsPyeong", 
    "PortfolioTransactions", "HotelFranchise", "PartialInterestType", "Beds"
]

# Load CSV
df = pd.read_csv(f'RCA_Transactions.csv', usecols=columns_to_load, low_memory=False)

# Drop rows with all NaN values
df.dropna(axis=0, how="all", inplace=True) 

def split_camel_case(text):
    # Koristi regularni izraz za rastavljanje stringa gde je veliko slovo
    return re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

df.columns = [split_camel_case(col) for col in df.columns]

df.columns = df.columns.str.lower()

df.columns = df.columns.str.replace(' ', '_')

df = df.rename(columns={
    'last_modified_date_string': 'last_modified_date', 
    'status_date_string': 'status_date',
    'create_date_string': 'create_date'})

In [60]:
def clean_string(string, remove_list, format_to_int: bool = False, format_to_float: bool = False, col_name: str = ''):
    # Check if the string is np.nan
    if isinstance(string, float) and np.isnan(string):
        return np.nan
    
    if string is None:
        return np.nan 
 
    # Remove all strings from the list starting with the given string 
    for item in remove_list:
        string = string.replace(item, "")
    
    # If the value is true, convert it to an integer
    if format_to_int:
        return to_int(string, col_name)
    
    # If the value is true, convert it to a float
    if format_to_float:
        return to_float(string, col_name)
     
    return string

def to_int(string, col_name: str = ''):
    # Check if the remaining string can be converted to an integer 
    try: 
        return int(string)
    except ValueError:
        print(f'To Int Error: {string}, Col Name: {col_name}')
        return np.nan
    
def to_float(string, col_name: str = ''): 
    # Check if the remaining string can be converted to a float
    try: 
        return float(string)
    except ValueError:
        print(f'To Float Error: {string}, Col Name: {col_name}')
        return np.nan
    
# Function to clean HTML tags using BeautifulSoup
def clean_html(text):
    if pd.isna(text) or text == '':
        return np.nan
    if '<' in text:  # This indicates the presence of HTML tags
        text = BeautifulSoup(text, "html.parser").get_text()  # Remove HTML tags
    return text

# Function to handle multiple values split by `;` and clean each one
def clean_and_split(text):
    if pd.isna(text) or text == '':
        return np.nan
    # Split by `;` and clean each part
    parts = text.split(' ; ')
    cleaned_parts = [clean_html(part) for part in parts]
    return ' ; '.join(cleaned_parts)  # Join back with ';'

# Function to safely evaluate the string
def safe_literal_eval(val):
    if isinstance(val, str):
        try:
            return ast.literal_eval(val)
        except (ValueError, SyntaxError):
            return val  # Return the original value if it cannot be evaluated
    return val

def clean_list(value, format_to_int: bool = False, format_to_float: bool = False, col_name: str = ''): 
    if pd.isna(value):  
        return np.nan  # If it is already NaN, return NaN immediately
    
    try:
        # Convert the string to a list if possible
        value_list = ast.literal_eval(value) if isinstance(value, str) else value
        
        # If it's not a list, return NaN
        if not isinstance(value_list, list):
            return np.nan

        # Filter out empty values
        cleaned_list = [item for item in value_list if item not in [None, '', 'None']]

        # If it needs to be converted to int, do so
        if format_to_int:
            cleaned_list = [to_int(item, col_name) for item in cleaned_list if not pd.isna(to_int(item, col_name))]
            return cleaned_list if cleaned_list else np.nan

        # If it needs to be converted to float, do so
        if format_to_float:
            cleaned_list = [to_float(item, col_name) for item in cleaned_list if not pd.isna(to_float(item, col_name))]
            return cleaned_list if cleaned_list else np.nan
        
        # If the list is now empty, return NaN
        return cleaned_list if cleaned_list else np.nan
    except Exception as e:
        print(f'[Clean List Error] Value: {value} is not valid. Column: {col_name}. Error: {e}')
        return np.nan  # If parsing fails, return NaN
    
# Function to split the string into a list based on multiple delimiters
def split_string(value, delimiters=[',', ';']):  
    if pd.isna(value):
        return np.nan
     
    if isinstance(value, str) and value.strip(): 
        pattern = f"[{''.join(map(re.escape, delimiters))}]+"
         
        split_values = [item.strip() for item in re.split(pattern, value) if item.strip() and item.strip().lower() != 'nan']
         
        return split_values if split_values else np.nan

    return value

In [61]:
print(df.columns)
print(f'Columns count: {len(df.columns)}')

Index(['_id', 'buyer_capital_group', 'seller_capital_group', 'property_id',
       'deal_id', 'property_key_id', 'longitude', 'latitude',
       'geo_code_quality', 'transaction_status', 'transaction_type',
       'transaction_subtype', 'status_date', 'last_modified_date',
       'property_type', 'property_type_full', 'property_type_code',
       'property_type_abbreviated', 'property_sub_type',
       'property_type_search_ids', 'construction_status_id', 'market',
       'sub_market', 'property_name', 'address', 'city', 'state_prov',
       'county', 'country', 'country_code', 'postal_code', 'create_date',
       'is_measurement_units', 'units', 'sf', 'units_combined',
       'number_buildings', 'number_floors', 'status_price',
       'status_price_adjusted', 'status_price_qualifier',
       'status_price_per_unit', 'status_price_per_sf', 'status_cap_rate',
       'status_cap_rate_qualifier', 'buyer_seller_broker_string',
       'property_comments', 'deal_comments', 'year_built', 'year_renovated',
       'qscore', 'feature', 'currency_id', 'measurement_id', 'deed', 'msa',
       'cbsa', 'land_area_acres', 'occupancy_rate', 'partial_interest_pct',
       'buildable_area_us', 'apns', 'buyers', 'sellers', 'lenders',
       'buyer_brokers', 'seller_brokers', 'has_portfolio', 'number_of_props',
       'mixed_property_type', 'first_mortgage_loan_amt',
       'prior_sale_price_amt', 'project_cost_amt', 'street_retail_area_dbl',
       'meeting_space_area_dbl', 'est_completion_date', 'is_cbd',
       'admin_level0id', 'admin_level1id', 'metro_id', 'trans_type_id',
       'tenants_full', 'tenants_metric', 'tenants_tsubo', 'tenants_pyeong',
       'portfolio_transactions', 'hotel_franchise', 'partial_interest_type',
       'beds'],
      dtype='object')
Columns count: 89

In [62]:
print(df['meeting_space_area_dbl'].count())
print(df['meeting_space_area_dbl'].dropna().head(100))

42
207      7000.0
210      3804.0
382      5000.0
568       888.0
691      4874.0
718     40000.0
969      5400.0
989     14841.0
1114      625.0
1247    10000.0
1359    50000.0
1681    10000.0
1749     1500.0
1770     1500.0
2057     7770.0
2113     1056.0
2162    48541.0
2173     8500.0
2677    14000.0
2697     6600.0
2934      340.0
3007    12000.0
3107      312.0
3263      350.0
3309    14200.0
3376    12000.0
3391    41000.0
3513     2730.0
3873    77600.0
3888      430.0
4050     1800.0
4134     1920.0
4137     2500.0
4264      600.0
4420     8000.0
4459     6800.0
4554      400.0
4773    42000.0
5013    15000.0
5068    12980.0
5092     2400.0
5431      892.0
Name: meeting_space_area_dbl, dtype: float64

In [ ]:
# Remove empty lists or items
for col in ['buyers', 'sellers', 'lenders', 'buyer_brokers', 'seller_brokers', 'portfolio_transactions']:
    df[col] = df[col].apply(lambda x: clean_list(str(x), col_name=col))  
     

# Ensure it remains a list of ints
for col in ['property_type_search_ids', 'number_floors']:
    df[col] = df[col].apply(lambda x: clean_list(str(x), format_to_int=True, col_name=col))
    

# Split string and convert to ast list
for col in ['apns']:
    df[col] = df[col].apply(lambda x: split_string(str(x), [',']))
    
# Split string and convert to ast list
for col in ['tenants_full', 'tenants_metric', 'tenants_tsubo', 'tenants_pyeong']:
    df[col] = df[col].apply(lambda x: split_string(str(x), [';'])) 

# pd.Datetime for import into Snowflake
for col in ['status_date', 'last_modified_date', 'create_date', 'est_completion_date']:
    df[col] = pd.to_datetime(df[col], errors='coerce', format='ISO8601')
    
# bools
for col in ['is_measurement_units', 'has_portfolio', 'mixed_property_type', 'is_cbd']:
    df[col] = df[col].apply(lambda x: x if x in [True, False] else np.nan)

# Ensure it remains a float
for col in ['longitude', 'latitude', 'units', 'sf', 'units_combined', 'status_price',
       'status_price_adjusted', 'status_price_per_unit', 'status_price_per_sf', 'status_cap_rate',
       'qscore', 'land_area_acres', 'occupancy_rate', 'partial_interest_pct', 'buildable_area_us',
       'first_mortgage_loan_amt', 'prior_sale_price_amt', 'project_cost_amt' 
       ]:
    df[col] = df[col].apply(lambda x: to_float(x, col_name=col))

# Ensure it remains a int
for col in ['_id', 'property_id', 'deal_id', 'geo_code_quality', 'construction_status_id',
            'postal_code', 'number_buildings', 'status_price_qualifier', 'status_cap_rate_qualifier', 
            'year_built', 'year_renovated', 'currency_id', 'measurement_id', 'deed', 'msa', 'cbsa',
            'number_of_props', 'street_retail_area_dbl', 'meeting_space_area_dbl',
            'admin_level0id', 'admin_level1id', 'metro_id', 'trans_type_id', 'beds'
            ]:
    df[col] = df[col].apply(lambda x: to_int(x, col_name=col))
    df[col] = df[col].astype(pd.Int64Dtype())
    

# Extract text from html 
for col in ['buyer_seller_broker_string', 'property_comments']:
    df[col] = df[col].apply(clean_and_split)
    
# Convert a list of strings into one string with commas in between
for col in ['apns']:  
    df[col] = df[col].apply(safe_literal_eval)  # Convert string to list safely
    df[col] = df[col].apply(lambda x: ', '.join(x) if isinstance(x, list) else x) 

# Clean
df['property_name'] = df['property_name'].replace('Unknown', np.nan)
df['buyer_seller_broker_string'] = df['buyer_seller_broker_string'].str.strip()
df['property_comments'] = df['property_comments'].str.replace(';;', '')
df['property_comments'] = df['property_comments'].str.strip()

# Scrape Date
df['Scrape_Date'] = pd.to_datetime('today').normalize()

df.to_csv('rca_transactions_output.csv', index=False)

[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1399777d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139974b50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139a269d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139a26c10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1397cbc50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1397e5650>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134851950>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13864d110>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13864e490>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13864ec50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13864cb50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138694390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13321b1d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13321b510>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13321aa10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138696190>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1385aab50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x114176f10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x10fe12f10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x10fe11890>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136eb61d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1397bf850>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139776a50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1397752d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136f1ee90>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136f1e410>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136f1d690>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136f1d050>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138829b90>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1388298d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13882b810>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13577a110>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13577a0d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136ebe290>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136d698d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1387c7fd0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135769010>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13576b450>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135766710>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135764d10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13885e350>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1395e4990>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1395e5990>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1376a9ed0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1395ab0d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138697110>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1397e7290>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1396be4d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139709410>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139708510>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1397402d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136db6e50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136db5690>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136beba10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132b92090>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x10f364cd0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132ac8910>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1356dc910>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1356dc390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1356de710>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13576d710>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1353f89d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1353fb010>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134728850>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13472bfd0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134729150>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1356d0950>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1356d3290>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135523c50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132bcecd0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1393d0090>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x137f33290>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1376b7810>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1376b6410>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1376b5110>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138483990>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138480950>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138480550>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138096ad0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1380941d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138096690>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138095390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x137c038d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x137c038d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132aab450>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132aab310>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138a73850>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138a706d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x138a706d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x137048d90>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x137048e10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x136eef390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132d99650>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132d9a6d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132ca36d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132ca0450>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132d2c0d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133cfea10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133cffe50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133cfdd50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133cfe2d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139aafe90>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139aaf610>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139aafc10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139aaead0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132d63cd0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132d5d290>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135427190>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133b50710>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133b53090>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135756590>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135756950>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133ae5390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133ae6ed0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133df8850>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1387cfb50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1387ccdd0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x139a78a10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133d17010>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133d03d50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133d02690>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1354cbd50>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1354caf90>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134d23390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134d21b10>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135751910>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133ced450>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133ced450>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133cee310>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x133cee310>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1332f87d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132b5b8d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1348eb110>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x1348e8a90>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132b67710>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13574d850>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13574d390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13574d390>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134609510>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x134609510>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x132b76850>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13a579ad0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13551e8d0>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13a579290>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x135503950>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13573f210>
[Clean List Error] Value: nan is not valid. Column: buyers. Error: malformed node or string on line 1: <ast.Name object at 0x13574b7d0>

In [64]:
print(df['property_comments'].count())
print(df['property_comments'].dropna().head(100))

5189
0                 Commercial property; buyer assumed mtg
1      Office - Sub property; Tenants: Southwest Key ...
2         Garden/Affordable property; prior sale: Sep-06
3                          Office - Sub/medical property
4      Centers/anchored/power center property; Tenant...
                             ...
102                                  Commercial property
103                                  Commercial property
104    Centers/anchored property; Tenants: Austin's C...
105                        Office - Sub/medical property
106                                   Warehouse property
Name: property_comments, Length: 100, dtype: object